export default {
  onboard1: require('./onboarding1.png'),
  onboard2: require('./onboarding2.png'),
  onboard3: require('./onboarding3.png'),
  rectangle: require('./rectangle.png'),
  examidcard: require('./examid.png'),
  success: require('./success.png'),
  bgHead: require('./bgHead.png'),
  map: require('./map.png'),
  mark: require('./marker.png'),
  iconAppDrone: require('./dronerIcon.png'),
  empty_droner: require('./empty_droner.png'),
  academy: require('./academy.png'),
  empty_farmer: require('./empty_farmer.png'),
  empty_plot: require('./empty_plot.png'),
  bg_droner: require('./bg_droner.png'),
  delete_acc: require('./delete_acc.png'),
  empty_droner_his: require('./empty_droner_history.png'),
  uncheck: require('./uncheck.png'),
  checked: require('./checked.png'),
  emptyTask: require('./emptyTask.png'),
};
