export default {
  check: require('./check.png'),
  checked: require('./ckecked.png'),
  th: require('./TH.png'),
  camera: require('./camera.png'),
  avatar: require('./avatar.png'),
  calendar: require('./calendar.png'),
  home: require('./home.png'),
  discount: require('./discount.png'),
  profile: require('./profile.png'),
  plots: require('./plots.png'),
  drone: require('./drone.png'),
  dangercircle: require('./dangercircle.png'),
  checkdisable: require('./checkdisable.png'),
  close: require('./x.png'),
  register: require('./register.png'),
  plot: require('./plot.png'),
  plant: require('./plant.png'),
  location: require('./location.png'),
  down:require('./down.png'),
  locate: require('./locate.png'),
  delete: require('./delete.png')
};