export default {
  arrowLeft : require('./arrow_left.png'),
  arrowRight : require('./arrow_right.png'),
  account: require('./account.png'),
  th: require('./TH.png'),
  deleteIcon: require('./deleteIcon.png'),
  camera: require('./camera.png'),
  check: require('./check.png'),
  checked: require('./checked.png'),
  jobCard: require('./jobcardsolid.png'),
  jobDistance: require('./jobcarddistance.png'),
  calling: require('./calling.png'),
  note: require('./note.png'),
  home: require('./home.png'),
  home_active: require('./home_active.png'),
  task: require('./task.png'),
  task_active: require('./task_active.png'),
  pocket: require('./pocket.png'),
  pocket_active: require('./pocket_active.png'),
  close: require('./x.png'),
  register: require('./register.png'),
  direction: require('./direction.png'),
  callSolid: require('./Calling-solid.png'),
  starfill: require('./starfill.png'),
  starCorner: require('./starCorner.png'),
  starBorder: require('./starBorder.png'),
  ssbaner: require('./ssbaner.png'),
  review: require('./review.png'),
  logout: require('./logout.png'),
  income : require('./income.png'),
  farm : require('./farm.png'),
  dronejob : require('./dronejob.png'),
  checkSolid: require('./check_solid.png'),
  profile:require('./Profile.png'),
  profileActive:require('./Profile-active.png'),
};
